### ISSUE TITLE
Multi Select Images in CameraRoll

### ISSUE THREAD

**Issue by slorse13** [fuse-x/studio#1]
It would be great to enable a multi select option for adding images.
Like this example:
https://forums.fusetools.com/t/pretty-image-uploader-with-php-server/7622

But there you only can select one Image.
Greetings!

**Comment by mortend** [comment]
Please submit feature requests related to Fuselibs functionality [here](https://github.com/fuse-open/fuselibs/issues), or ask in the forum (which I see you have already done, good). Closing.
