### ISSUE TITLE
Fuse X will not open or acknowledge any projects

### ISSUE THREAD

**Issue by sumrex** [fuse-x/studio#15]
New to this so maybe I set something up wrong.

I go to create a project and it makes files in the folder, however the launcher does not see any of the projects in "Recent Projects" and when I try to browse to them to open the .unoproj file nothing happens.
What is going wrong here?

**Comment by mortend** [comment]
Opening projects in Fuse X seems to work normally and we don't know how to reproduce this problem. Closing the ticket.

(Please provide more details and reopen the ticket is this is still a problem in more recent versions)
