### ISSUE TITLE
macOS installer doesn't detect node installed via macports

### ISSUE THREAD

**Issue by vvarp** [fuse-x/studio#16]
As title says - nodejs v12 is installed and available in `$PATH`:

```
~ % which node
/opt/local/bin/node
```

Unfortunately installer fails with message "This application requires 'node' version 10.0 or newer."

**Comment by EnguGH** [comment]
Hi,

same problem here, any update on that ?

**Comment by mortend** [comment]
Does it still not work on the latest version? The problem was addressed in 2.0.0-beta.11.

If it still doesn't work we'll need to investigate more.

**Comment by vvarp** [comment]
Yes, installer works now - thanks!

**Comment by mortend** [comment]
Cool! :)

**Comment by EnguGH** [comment]
OK, just understood that my problem was that node (and npm) were not in a standard `PATH` location (i.e. not in a path written in `/etc/paths`).
`ln -s /Users/USER/.nvm/versions/node/v12.20.1/bin/node /usr/local/bin/node` fixed it for me.

Thanks.
