### ISSUE TITLE
Windows installation failed with error npm not recognised as command

### ISSUE THREAD

**Issue by easy-and-simple** [fuse-x/studio#17]
Output folder: D:\TMP\fuse-setup
Extract: copy-unoconfig.js... 100%
Extract: wrap.cmd... 100%
vcredist 2010 (x64) is installed already
vcredist 2012 (x64) is installed already
vcredist 2013 (x64) is installed already
Installing Node.js
Execute: msiexec.exe /i "D:\TMP\fuse-setup\node-v14.15.4-x64.msi" /qn
Extract: fuse-x-studio-win-2.0.0-beta.10.tgz... 100%
Installing fuse-x-studio@2.0.0-beta.10
'npm' is not recognized as an internal or external command,
operable program or batch file.
Reinstalling fuse-x-studio@2.0.0-beta.10
'npm' is not recognized as an internal or external command,
operable program or batch file.
Delete file: D:\TMP\fuse-setup\fuse-x-studio-win-2.0.0-beta.10.tgz
Install failed.

**Comment by mortend** [comment]
We will try to fix that in a later version.

It is possible to install Node.js manually to work around this error.

https://nodejs.org/en/download/

**Comment by mortend** [comment]
This problem is fixed in versions 2.4.0 and up
