### ISSUE TITLE
android-build-tools fails to install, projects all appear blank and the application appears buggy.

### ISSUE THREAD

**Issue by 2SIX6** [fuse-x/studio#19]
Originally mis-posted this in /fuse-open/

**System Specs:**
Device name	#######
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	        #################
Product ID	##############
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

___LOG OUTPUT___
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'android-build-tools',
0 verbose cli   '-g',
0 verbose cli   '-f',
0 verbose cli   '--prefix',
0 verbose cli   'C:\\Users\\#####\\AppData\\Roaming\\npm'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\#####\AppData\Roaming\npm\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\#####\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\#####\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 warn using --force Recommended protections disabled.
27 timing npm:load Completed in 11ms
28 timing arborist:ctor Completed in 2ms
29 timing idealTree:init Completed in 3ms
30 timing idealTree:userRequests Completed in 1ms
31 silly idealTree buildDeps
32 silly fetch manifest android-build-tools@*
33 http fetch GET 200 https://registry.npmjs.org/android-build-tools 494ms (cache revalidated)
34 silly placeDep ROOT android-build-tools@1.5.3 OK for:  want: *
35 silly fetch manifest xbash@^1.6.0
36 http fetch GET 200 https://registry.npmjs.org/xbash 406ms (cache revalidated)
37 timing idealTree:#root Completed in 907ms
38 silly placeDep node_modules/android-build-tools xbash@1.6.0 OK for: android-build-tools@1.5.3 want: ^1.6.0
39 silly fetch manifest which@^2.0.2
40 http fetch GET 200 https://registry.npmjs.org/which 47ms (cache revalidated)
41 timing idealTree:node_modules/android-build-tools Completed in 50ms
42 silly placeDep node_modules/android-build-tools which@2.0.2 OK for: xbash@1.6.0 want: ^2.0.2
43 silly fetch manifest isexe@^2.0.0
44 http fetch GET 200 https://registry.npmjs.org/isexe 41ms (cache revalidated)
45 timing idealTree:node_modules/android-build-tools/node_modules/xbash Completed in 47ms
46 silly placeDep node_modules/android-build-tools isexe@2.0.0 OK for: which@2.0.2 want: ^2.0.0
47 timing idealTree:node_modules/android-build-tools/node_modules/which Completed in 4ms
48 timing idealTree:node_modules/android-build-tools/node_modules/isexe Completed in 0ms
49 timing idealTree:buildDeps Completed in 1010ms
50 timing idealTree:fixDepFlags Completed in 0ms
51 timing idealTree Completed in 1017ms
52 timing reify:loadTrees Completed in 1018ms
53 timing reify:diffTrees Completed in 0ms
54 silly reify moves {}
55 timing reify:retireShallow Completed in 0ms
56 timing reify:createSparse Completed in 2ms
57 timing reify:loadBundles Completed in 0ms
58 silly audit bulk request {
58 silly audit   'android-build-tools': [ '1.5.3' ],
58 silly audit   xbash: [ '1.6.0' ],
58 silly audit   which: [ '2.0.2' ],
58 silly audit   isexe: [ '2.0.0' ]
58 silly audit }
59 timing reifyNode:node_modules/android-build-tools/node_modules/xbash Completed in 18ms
60 timing reifyNode:node_modules/android-build-tools Completed in 19ms
61 timing reifyNode:node_modules/android-build-tools/node_modules/which Completed in 19ms
62 timing reifyNode:node_modules/android-build-tools/node_modules/isexe Completed in 21ms
63 timing reify:unpack Completed in 21ms
64 timing reify:unretire Completed in 0ms
65 timing build:queue Completed in 1ms
66 timing build:link:node_modules/android-build-tools/node_modules/which Completed in 4ms
67 timing build:link:node_modules/android-build-tools/node_modules/xbash Completed in 4ms
68 timing build:link Completed in 4ms
69 info run android-build-tools@1.5.3 install node_modules/android-build-tools xbash src/install.bash
70 info run android-build-tools@1.5.3 install { code: 1, signal: null }
71 timing reify:rollback:createSparse Completed in 7ms
72 timing reify:rollback:retireShallow Completed in 0ms
73 timing command:install Completed in 1173ms
74 verbose stack Error: command failed
74 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
74 verbose stack     at ChildProcess.emit (node:events:390:28)
74 verbose stack     at maybeClose (node:internal/child_process:1064:16)
74 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
75 verbose pkgid android-build-tools@1.5.3
76 verbose cwd C:\Program Files\fuse X
77 verbose Windows_NT 10.0.22000
78 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "android-build-tools" "-g" "-f" "--prefix" "C:\\Users\\#####\\AppData\\Roaming\\npm"
79 verbose node v16.13.0
80 verbose npm  v8.1.0
81 error code 1
82 error path C:\Users\#####\AppData\Roaming\npm\node_modules\android-build-tools
83 error command failed
84 error command C:\WINDOWS\system32\cmd.exe /d /s /c xbash src/install.bash
85 error ERROR: 'bash.exe' was not found. This can be solved by installing Git.
85 error
85 error Please get Git from https://git-scm.com/downloads and try again.
86 verbose exit 1
___END LOG____

it should be noted that both Git and node.js are installed and working.

**Comment by 2SIX6** [comment]
Okay, was able to get everything installed by uninstalling git, reinstalling it and adjusting some of the parameters, and also manually installing JDK8 _PRIOR_ to running the fuse installer.


^^^This is on a windows 11 machine by the way^^^

**Comment by mortend** [comment]
Nice, thanks for the report!
