### ISSUE TITLE
android install issue

### ISSUE THREAD

**Issue by yhyundrmit** [fuse-x/studio#2]
i want install android.
and i write fuse install android
it say to me 'Done installing android' in 10 seconds.
so i write 'uno build -t=android -c=debug'

but it make error.

see down. thank you.

fuse X 2021 version 2.0.0-beta.2
Starting android installer
Done installing android

C:\Users\YYH\Documents\Fuse\App11>uno build -t=android -c=debug
Uno 2.0.0-beta.4 (build 814) Windows 10 x64 775177d
Copyright (C) 2018-present Fuse Open

Configuring  1.61 s
Installing dependencies  3.33 s
Compiling syntax tree  1.63 s
Generating code and data  4.98 s
Building android app
ERROR: Could not locate the Android SDK or NDK.

These dependencies can be acquired by installing 'android-build-tools':

    npm install android-build-tools -g

After installing, pass --force to make sure the new configuration is picked up.

    uno build android --force

(unknown): E0200: android build failed
> 4.26 s

Build failed in 15.83 seconds
    1 error

**Comment by mortend** [comment]
This issue will (hopefully) be fixed by https://github.com/fuse-open/uno/pull/361.

Thank you for testing fuse X!

**Comment by mortend** [comment]
This is addressed by [beta.5](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.5). (Please reopen the issue if not resolved)
