### ISSUE TITLE
Mac test - fuse X 2.0.0-beta.4 - closing app causes high CPU usage

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-x/studio#5]
Howsit! Hope you keeping well!

So here's my initial experience with 2.0.0-beta.4:

- macOS Catalina (10.15.7)
- I previously updated my mono to the latest stable version today because I was going to test the latest version of Uno too

1. Package install was successful (felt a little long near the end, wasn't sure if it was still installing as the bar didn't look like it was moving but I gave it the benefit of the doubt before seeing green :)
2. It opened, I created an example project, saw the purchase license screen, I then used `fuse uri fusestudio://license/[code]` in a terminal, which ended with "ok".
3. I didn't notice a change, so I tried to close fuseX (cmd+q), that's when everything went crazy; fuseX got the color wheel of death, my CPU usage went up and the OS practically froze, had to do a hardware reboot.
4. After I rebooted and started up fuseX again, it went in fine, was able to open the project again.
5. Every time I try to close fuseX, my CPU usage sky rockets to around 130%, then about 2-5mins later, it finally exits and drops back down.

**Comment by mortend** [comment]
This is addressed by [beta.5](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.5). (Please reopen the issue if not resolved)
