### ISSUE TITLE
Mac app does not start

### ISSUE THREAD

**Issue by weggis** [fuse-x/studio#6]
App started first time after install, but after reboot it wont.. Icon starts jumping in dock (starting), but quits without any error.

Installed;
Node v12.19.0 LTS
Mono v6.10.0
Visual Studio for Mac

**Comment by mortend** [comment]
This is addressed by [beta.5](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.5). (Please reopen the issue if not resolved)
