### ISSUE TITLE
Project will not load on Mac

### ISSUE THREAD

**Issue by weggis** [fuse-x/studio#7]
After opening a project, editor is stuck on "Loading project..." (or something like that). Never gets to the preview/edit mode.

Installed;
Node v12.19.0 LTS
Mono v6.10.0
Visual Studio for Mac

**Comment by mortend** [comment]
This is addressed by [beta.5](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.5). (Please reopen the issue if not resolved)
