### ISSUE TITLE
Cannot build IOS app (from Mac)

### ISSUE THREAD

**Issue by weggis** [fuse-x/studio#8]
When trying to build an iOS app from terminal (fuse build ios), I get the following errors;

You are using dlopen without a full path, retrying by prepending /usr/lib
Error: Invalid values in ArrangeMarginBox
	In: Fuse.Controls.Rectangle (src/Components/RegTextInput.TextInput.ux:5)
	Fuse: /usr/local/lib/node_modules/@fuse-x/studio-mac/node_modules/@fuse-open/fuselibs/Source/build/Fuse.Elements/2.0.0-beta.1/Element.Layout.uno:262
Error: non-square pixelsPerOSPoint: 1.602667, 1.1994
	Fuse: /usr/local/lib/node_modules/@fuse-x/studio-mac/node_modules/@fuse-open/fuselibs/Source/build/Fuse.Nodes/2.0.0-beta.1/RootViewport.uno:205

Installed;
Node v12.19.0 LTS
Mono v6.10.0
Visual Studio for Mac

**Comment by weggis** [comment]
Errors were not relevant..

**Comment by weggis** [comment]
Correct error messages when trying to build iOS:

You are using dlopen without a full path, retrying by prepending /usr/lib
Generating code and data  6.62 s ⠏Could not find `PresentationCore` referenced by assembly `QRCoder, Version=1.3.9.0, Culture=neutral, PublicKeyToken=null`.
Could not find `PresentationCore` referenced by assembly `fuse-studio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null`.
Could not find `PresentationCore` referenced by assembly `Outracks.Fuse.Command, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null`.
Could not find `PresentationCore` referenced by assembly `fuse, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null`.
Generating code and data  6.67 s                                               
FATAL ERROR: Could not load the file 'PresentationCore'. (pass --trace for stack trace)

**Comment by ichan-mb** [comment]
Generating Fuse Preview on the mac still have some issue, but you can build the app instead using: `fuse build ios` or `fuse build android`

**Comment by mdings** [comment]
Same errors here when building for ios

`FATAL ERROR: Could not load the file 'PresentationCore'. (pass --trace for stack trace)`

**Comment by mortend** [comment]
A fix for this will be included in the upcoming 2.0.0-beta.5, coming soon.

**Comment by mortend** [comment]
This is addressed by [beta.5](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.5). (Please reopen the issue if not resolved)
